name: Github-actions-Node.js

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: |
          npm run build
          npm t
        
